package site.komuna.reserve.common.httpError

enum class ReserveErrorType {
    INTERNAL_SERVER_ERROR,
    INVALID_SETTINGS_KEY,
    INVALID_SETTINGS_VALUE,
    CANNOT_PERFORM_THAT_ACTION,
    INVALID_CREDENTIALS,
    TOKEN_REFRESH_INVALID,
    EMAIL_TAKEN,
    EMAIL_NOT_CONFIRMED,
    EMAIL_ALREADY_VERIFIED,
    EMAIL_VERIFICATION_TOKEN_EXPIRED,
    USER_NOT_FOUND,
    USER_BANNED,
    USER_IS_NOT_MEMBER_OF_ORGANIZATION,
    USER_IS_MEMBER_OF_ORGANIZATION,
    ORGANIZATION_NOT_FOUND,
    ORGANIZATION_LAST_OWNER,
    RESERVATION_TYPE_NOT_FOUND,
    RESERVATION_STATUS_NOT_FOUND,
    RESERVATION_CANCEL_DETAILS_NOT_FOUND,
    RESERVATION_NOT_FOUND,
    ROOM_NOT_FOUND,
    ROLE_NOT_FOUND,
    MISSING_DATA,
    VALIDATION_ERROR,
    CANNOT_GET_THAT_SETTING_VALUE
}