spring.application.name=reserve

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/reserv
spring.datasource.username=lukasz
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update