spring.application.name=reserve

server.port=8443
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:local-dev.p12
server.ssl.key-store-password=changeit


spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/reserv
spring.datasource.username=reserve
spring.datasource.password=tYcqib-saqnos-nivvu0

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.placeholder-replacement=false

tokens.secret=45054652-6c92-457a-8a7b-1ea9e3d48ef8
tokens.access-expiration-minutes=${RESERVE_TOKENS_ACCESS_EXPIRATION_MINUTES:60}
tokens.refresh-expiration-days=${RESERVE_TOKENS_REFRESH_EXPIRATION_DAYS:30}
tokens.validation-expiration-minutes=${RESERVE_TOKENS_VALIDATION_EXPIRATION_MINUTES:15}
