spring.application.name=reserve

server.port=8443
#server.ssl.enabled=true
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=classpath:local-dev.p12
#server.ssl.key-store-password=changeit


spring.datasource.url=jdbc:postgresql://postgres:5432/reserve
spring.datasource.username=reserve
spring.datasource.password=tYcqib-saqnos-nivvu0


spring.jpa.hibernate.ddl-auto=validate
spring.flyway.placeholder-replacement=false

tokens.secret=45054652-6c92-457a-8a7b-1ea9e3d48ef8
tokens.access-expiration-minutes=${RESERVE_TOKENS_ACCESS_EXPIRATION_MINUTES:60}
tokens.refresh-expiration-days=${RESERVE_TOKENS_REFRESH_EXPIRATION_DAYS:30}
tokens.validation-expiration-minutes=${RESERVE_TOKENS_VALIDATION_EXPIRATION_MINUTES:15}

# Actuator Web Exposure
management.endpoints.web.exposure.include=health,info,metrics,env
management.endpoint.health.show-details=always

# Enable Built-in Info Contributors
management.info.env.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true
management.info.build.enabled=true
management.info.git.enabled=true
management.info.git.mode=full

# Custom Static Info Metadata
info.app.name=Reserve API
info.app.description=VipSound Rehearsal Room Booking Engine
info.app.version=@project.version@