package site.komuna.reserve.sse

enum class ReserveEvents {
    RESERVATION_CREATED,
    RESERVATION_REJECTED,
    RESERVATION_CONFIRMED,
    RESERVATION_CANCELED,
    RESERVATION_CANCEL_REQUESTED,
    RESERVATION_CANCEL_REJECTED;
}