package site.komuna.reserve.email.model

enum class EmailTemplateType {
    ACTIVATION_EMAIL,
    USER_RESERVATION_CREATED,
    CHANGED_PASSWORD,
    REMIND_PASSWORD,
    USER_BANNED,
    RESERVATION_CREATED_PRIVATE,
    RESERVATION_CREATED_ORGANIZATION,
    RESERVATION_REMINDER,
    RESERVATION_CANCEL_REQUESTED,
    RESERVATION_CANCELED_PRIVATE,
    RESERVATION_CANCELED_ORGANIZATION,
    RESERVATION_REJECTED,
    RESERVATION_CONFIRMED,
    RESERVATION_CANCEL_REJECTED
}