ALTER TABLE settings
    ADD COLUMN database_only BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE settings
SET database_only = TRUE
WHERE key IN (
    'MAIL_SERVER_HOST',
    'MAIL_SERVER_PORT',
    'MAIL_SMTP_AUTH',
    'MAIL_SMTP_STARTTLS_ENABLE',
    'MAIL_SERVER_USERNAME',
    'MAIL_SERVER_BETA_ADDRESS',
    'MAIL_SERVER_PASSWORD'
);