CREATE TABLE privacy_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT,
    date TIMESTAMP(6) WITH TIME ZONE
);

INSERT INTO privacy_policies (content, date) VALUES ('<p>Privacy policy</p>', now());