create table email_fragments
(
    name       varchar(255) not null
        primary key,
    fragment text,
    type     varchar(255)
        constraint email_fragments_type_check
            check ((type)::text = ANY
                   (ARRAY [('HEADER'::character varying)::text, ('BODY'::character varying)::text, ('FOOTER'::character varying)::text]))
);

create table email_templates
(
    name      varchar(255) not null
        primary key,
    language  varchar(2),
    subject   varchar(255),
    type      varchar(255)
        constraint email_templates_type_check
            check ((type)::text = ANY
                   (ARRAY [('ACTIVATION_EMAIL'::character varying)::text, ('USER_RESERVATION_CREATED'::character varying)::text])),
    body_id   varchar(255) not null
        constraint fk7jk93wmceso6e899lx5o31qpe
            references email_fragments,
    footer_id varchar(255)
        constraint fkqta1g6fwiuxsqod83pleoafpu
            references email_fragments,
    header_id varchar(255)
        constraint fks2imjjwvyy34hqvqgjphw5nkb
            references email_fragments
);

create table rooms
(
    id            bigint generated by default as identity
        primary key,
    is_recordable boolean not null,
    name          varchar(255)
);

create table settings
(
    key          varchar(255) not null
        primary key
        constraint settings_key_check
            check ((key)::text = ANY
                   ((ARRAY ['RESERVATION_CANCELLATION_WITHOUT_APPROVAL_HOURS'::character varying, 'MAIL_SERVER_HOST'::character varying, 'MAIL_SERVER_PORT'::character varying, 'MAIL_SERVER_USERNAME'::character varying, 'MAIL_SERVER_PASSWORD'::character varying, 'MAIL_SMTP_AUTH'::character varying, 'MAIL_SMTP_STARTTLS_ENABLE'::character varying, 'MAIL_SERVER_BETA_ADDRESS'::character varying])::text[])),
    is_sensitive boolean      not null,
    value        varchar(255)
);

create table users
(
    id                 bigint generated by default as identity
        primary key,
    created            timestamp(6) with time zone,
    email              varchar(255),
    nick               varchar(255),
    password           varchar(255),
    password_changed   timestamp(6) with time zone,
    preferred_language varchar(255),
    role               varchar(255)
        constraint users_role_check
            check ((role)::text = ANY
                   ((ARRAY ['USER'::character varying, 'MANAGER'::character varying, 'ADMIN'::character varying, 'SYSTEM'::character varying])::text[])),
    trusted            boolean not null
);

create table bans
(
    id                bigint generated by default as identity
        primary key,
    ban_expires       timestamp(6) with time zone,
    banned_at         timestamp(6) with time zone,
    reason            varchar(255),
    banned_by_user_id bigint not null
        constraint fka31uk40mt4ga8bag2dc01hi8v
            references users,
    user_id           bigint not null
        constraint fkdshp5tj95xpg7ikybc4teb68q
            references users
);

create table organizations
(
    id                 bigint generated by default as identity
        primary key,
    created            timestamp(6) with time zone,
    name               varchar(255),
    trusted            boolean not null,
    created_by_user_id bigint  not null
        constraint fkmlo60nuqseyryax3g38jxx70g
            references users
);

create table organization_members
(
    id               bigint generated by default as identity
        primary key,
    added_at         timestamp(6) with time zone,
    role             varchar(255)
        constraint organization_members_role_check
            check ((role)::text = ANY ((ARRAY ['OWNER'::character varying, 'MEMBER'::character varying])::text[])),
    added_by_user_id bigint not null
        constraint fkhu6q4ap22wvter2m0i6jv9326
            references users,
    organization_id  bigint not null
        constraint fk7vpc2vd3jlfahlombjdc32mhe
            references organizations,
    user_id          bigint not null
        constraint fk67edx4b35ogkpk3ghbhwand9i
            references users,
    constraint ukiudqo8es7i8crk2m1q4obn6r0
        unique (organization_id, user_id)
);

create table pricing
(
    id               bigint generated by default as identity
        primary key,
    price            integer not null,
    reservation_type varchar(255)
        constraint pricing_reservation_type_check
            check ((reservation_type)::text = ANY
                   ((ARRAY ['REHEARSAL'::character varying, 'RECORDING'::character varying])::text[])),
    valid_from       timestamp(6) with time zone,
    changed_by_id    bigint
        constraint fkj790gp541hb0j8ul8tgndc4ws
            references users,
    room_id          bigint
        constraint fksor4fmughdf31sxwlku06ctat
            references rooms
);

create table refresh_tokens
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) with time zone,
    expires    timestamp(6) with time zone,
    token      varchar(255),
    user_id    bigint not null
        constraint fk1lih5y2npsf8u5o3vhdb9y0os
            references users
);

create table reservations
(
    id                  bigint generated by default as identity
        primary key,
    end_at              timestamp(6) with time zone,
    reserved_at         timestamp(6) with time zone,
    start_at            timestamp(6) with time zone,
    status              varchar(255)
        constraint reservations_status_check
            check ((status)::text = ANY
                   ((ARRAY ['CREATED'::character varying, 'CONFIRMED'::character varying, 'REJECTED'::character varying, 'REQUESTED_CANCELLATION'::character varying, 'CANCELLED'::character varying, 'REJECTED_CANCELLATION'::character varying])::text[])),
    type                varchar(255)
        constraint reservations_type_check
            check ((type)::text = ANY
                   ((ARRAY ['REHEARSAL'::character varying, 'RECORDING'::character varying])::text[])),
    organization_id     bigint
        constraint fkajewrwesrpyp6da6d61p0te4s
            references organizations,
    reserved_by_user_id bigint not null
        constraint fk87m3pw2re3ltxhfscf2fiqawb
            references users,
    room_id             bigint not null
        constraint fkljt6q1tp205b0h26eiegc5mx6
            references rooms
);

create table reservation_cancel
(
    id             bigint generated by default as identity
        primary key,
    approved_at    timestamp(6) with time zone,
    requested_at   timestamp(6) with time zone,
    approved_by    bigint
        constraint fkqgtravfnwlb8c0lgq22cq6165
            references users,
    requested_by   bigint not null
        constraint fkp9s0u30vgdsc764e8tprc0l5f
            references users,
    reservation_id bigint not null
        constraint uke2mrw1q44nmfll4owoswlno13
            unique
        constraint fkiywjx6udvyn6g23k2v0qvi4ec
            references reservations
);

create table reservation_confirm
(
    id             bigint generated by default as identity
        primary key,
    approved_at    timestamp(6) with time zone,
    approved_by    bigint
        constraint fkaig080hp79vulcqj1xt3y5o6d
            references users,
    reservation_id bigint not null
        constraint uk9yw6shmgo7lrn13th0v7kcsjx
            unique
        constraint fkb11kjht8qp2txg8ubts0pw5e2
            references reservations
);

create table verification_tokens
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) with time zone,
    expires    timestamp(6) with time zone,
    token      varchar(255),
    user_id    bigint not null
        constraint ukdqp95ggn6gvm865km5muba2o5
            unique
        constraint fk54y8mqsnq1rtyf581sfmrbp4f
            references users
);

INSERT INTO public.users (id, created, email, nick, password, password_changed, preferred_language, role, trusted) VALUES (1, '2026-08-11 19:56:29.489807 +00:00', '', 'SYSTEM', '', null, 'pl', 'SYSTEM', false);

INSERT INTO public.rooms (id, name, is_recordable) VALUES (1, 'Duża', true);
INSERT INTO public.rooms (id, name, is_recordable) VALUES (2, 'Środkowa', false);
INSERT INTO public.rooms (id, name, is_recordable) VALUES (3, 'Tylnia', false);

INSERT INTO public.pricing (id, price, reservation_type, valid_from, changed_by_id, room_id) VALUES (1, 100, 'RECORDING', '2026-08-09 17:51:15.849437 +00:00', 1, 1);
INSERT INTO public.pricing (id, price, reservation_type, valid_from, changed_by_id, room_id) VALUES (2, 50, 'REHEARSAL', '2026-08-09 17:51:27.328922 +00:00', 1, 1);
INSERT INTO public.pricing (id, price, reservation_type, valid_from, changed_by_id, room_id) VALUES (3, 50, 'REHEARSAL', '2026-08-09 17:51:32.896016 +00:00', 1, 2);
INSERT INTO public.pricing (id, price, reservation_type, valid_from, changed_by_id, room_id) VALUES (4, 50, 'REHEARSAL', '2026-08-09 17:51:36.770200 +00:00', 1, 3);

SELECT setval(
   pg_get_serial_sequence('users', 'id'),
   (SELECT COALESCE(MAX(id), 1) FROM users)
);

SELECT setval(
   pg_get_serial_sequence('rooms', 'id'),
   (SELECT COALESCE(MAX(id), 1) FROM rooms)
);

SELECT setval(
   pg_get_serial_sequence('pricing', 'id'),
   (SELECT COALESCE(MAX(id), 1) FROM pricing)
);