INSERT INTO public.email_fragments (name, fragment, type) VALUES ('header', e'<tr> <td bgcolor="#000000" style=" background-color: #000000; padding: 12px 24px;"> <img src="cid:logo" alt="Logo" width="160" style="display:block; width:160px; max-width:160px; height:auto; border:0;"> </td> </tr>', 'HEADER');

INSERT INTO public.email_fragments (name, fragment, type) VALUES ('Activation Code pl', e'<tr> <td style="background-color: #ffffff; padding: 40px; font-family: Arial, Helvetica, sans-serif; color: #333333;"> <h1 style=" margin-top: 0; text-align: center;"> ${nick} witaj w VipSound! </h1> <p> Na razie Twoje konto nie jest jeszcze aktywne. Użyj linku poniżej aby je aktywować i rezerwować sale </p> <a href="https://127.0.0.1:8443/auth/confirmEmail/${verificationToken}"> AKTYWUJ KONTO </a> </td> </tr>', 'BODY');
INSERT INTO public.email_fragments (name, fragment, type) VALUES ('Activation Code en', e'<tr> <td style="background-color: #ffffff; padding: 40px; font-family: Arial, Helvetica, sans-serif; color: #333333;"> <h1 style="margin-top: 0; text-align: center;"> Welcome to VipSound, ${nick}! </h1> <p>Your account is not active yet. Please use the link below to activate your account and start booking rooms.</p> <a href="https://127.0.0.1:8443/auth/confirmEmail/${verificationToken}"> ACTIVATE ACCOUNT </a> </td> </tr>', 'BODY');

INSERT INTO public.email_fragments (name, fragment, type) VALUES ('Footer pl', e'<tr> <td style="background-color: #f5f5f5; padding: 24px; text-align: center; font-family: Arial, Helvetica, sans-serif; font-size: 12px; color: #777777;"> <p style="margin: 0;"> © 2026 Komuna Reserve </p> <p style="margin: 8px 0 0 0;"> Ta wiadomość została wygenerowana automatycznie. Prosimy na nią nie odpowiadać. </p> </td> </tr>', 'FOOTER');
INSERT INTO public.email_fragments (name, fragment, type) VALUES ('Footer en', e'<tr> <td style="background-color: #f5f5f5; padding: 24px; text-align: center; font-family: Arial, Helvetica, sans-serif; font-size: 12px; color: #777777;"> <p style="margin: 0;">© 2026 Komuna Reserve</p><p style="margin: 8px 0 0 0;">This message was generated automatically. Please do not reply to this email.</p></td></tr>','FOOTER');

INSERT INTO public.email_templates (name, body_id, footer_id, header_id, language, subject, type) VALUES ('Activation Code en', 'Activation Code en', 'Footer en', 'header', 'en', 'VipSound account activation', 'ACTIVATION_EMAIL');
INSERT INTO public.email_templates (name, body_id, footer_id, header_id, language, subject, type) VALUES ('Activation Code pl', 'Activation Code pl', 'Footer pl', 'header', 'pl', 'VipSound aktywacja konta', 'ACTIVATION_EMAIL');